name: robomimic
args: []
kwargs: 
  task_name: "square"

dataset:
  _target_: "datasets.robomimic_dset.load_robomimic_slice_test"
  data_path: "/coc/flash7/bli678/projects/egowm/data/robomimic_datasets/square/embodiments/image_64_shaped_done1_v141_kinova3.hdf5"
  task_name: "square"
  normalize_action: False
  n_rollout: null
  done_mode: 1  # Done mode (0, 1, or 2)
  shape_rewards: True
  img_size: ${img_size}
  max_traj_length: 250
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16